name: Release Gem on RubyGems.org

on:
  push:
    tags:
        - v*
  workflow_dispatch:

jobs:
  release:
    name: Release to RubyGems
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rails-diff-time

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true

      - name: Release Gem
        uses: rubygems/release-gem@v1
